#!/usr/bin/env zsh
bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 11 12 13 14 15

bspc config border_width 0
bspc config window_gap 4

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config focus_follows_pointer false
bspc config pointer_follows_monitor false
bspc config click_to_focus true
bspc config remove_disabled_monitors true
bspc config presel_feedback_color "#000000"

wmname LG3D

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

sxhkd &

polybar main -r &

compton --config ~/.config/compton/compton.conf &

xclip &

if [[ -z "${DBUS_SESSION_BUS_ADDRESS}" ]]; then
	# Export dbus env vars
	eval `dbus-launch --sh-syntax --exit-with-session`
	echo "D-Bus per-session daemon address is: ${DBUS_SESSION_BUS_ADDRESS}"
fi

# https://wiki.archlinux.org/index.php/GNOME/Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
