#!/usr/bin/env zsh
bspc monitor LVDS1 -d 1 2 3 4 5

#bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width 0
bspc config window_gap 5

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config focus_follows_pointer false
bspc config pointer_follows_monitor false
bspc config click_to_focus true
bspc config remove_disabled_monitors true
bspc config presel_feedback_color "#000000"

wmname LG3D

#polybar main -r &
polybar laptop -r &

compton --config ~/.config/compton/compton.conf &
sxhkd &
